version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.10
        environment: 
          
    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install

      - run: yarn test

      - run: yarn build

      - save_cache: 
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  deploy:
      docker:
        - image: circleci/node:10.10

      working_directory: ~/repo

      steps:
        - restore_cache:
                  key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        
        - run:
            name: Install AWS CLI
            command:
                sudo apt-get -y -qq install awscli

        - run:
            name: Set S3 Bucket Env Variable
            command: |
                echo 'export AWS_BUCKET=${AWS_BUCKET}' >> $BASH_ENV
                source $BASH_ENV

        - run:
            name: Deploy to S3
            command: aws s3 sync dist s3://${AWS_BUCKET}

workflows:
  version: 2
  build_and_deploy_staging:
      jobs:
        - build:
            filters:
                tags:
                    ignore: /.*/
            context: staging
        - deploy:
            requires:
                - build
            filters:
                tags:
                    ignore: /.*/
                branches:
                  only:
                    - master
            context: staging
  build_and_deploy_production:
      jobs:
        - build:
            filters:
                tags:
                    only: /^v.*/
                branches:
                    ignore: /.*/
            context: production
        - deploy:
            requires:
                - build
            filters:
                tags:
                    only: /^v.*/
                branches:
                    ignore: /.*/
            context: production
            


